### ISSUE TITLE
`pa11y-ci` Error: Page crashed!

### ISSUE THREAD

**Issue by DaveSkender** [GSA/digitalcorps.gsa.gov#18]
## Describe the bug

Intermittently, `pa11y-ci` tests crash in the build.
Follow https://github.com/pa11y/pa11y-ci/issues/128 and https://github.com/pa11y/pa11y-ci/issues/168 for upstream fixes.

Error message(s):

```console
Running Pa11y on 5 URLs:
(node:1714) UnhandledPromiseRejectionWarning: Error: Page crashed!
    at Page._onTargetCrashed (/home/runner/work/digitalcorps.gsa.gov/digitalcorps.gsa.gov/node_modules/puppeteer/lib/Page.js:215:24)
    at CDPSession.<anonymous> (/home/runner/work/digitalcorps.gsa.gov/digitalcorps.gsa.gov/node_modules/puppeteer/lib/Page.js:123:56)
    at CDPSession.emit (events.js:400:28)
    at CDPSession._onMessage (/home/runner/work/digitalcorps.gsa.gov/digitalcorps.gsa.gov/node_modules/puppeteer/lib/Connection.js:200:12)
    at Connection._onMessage (/home/runner/work/digitalcorps.gsa.gov/digitalcorps.gsa.gov/node_modules/puppeteer/lib/Connection.js:112:17)
    at WebSocket.<anonymous> (/home/runner/work/digitalcorps.gsa.gov/digitalcorps.gsa.gov/node_modules/puppeteer/lib/WebSocketTransport.js:44:24)
    at WebSocket.onMessage (/home/runner/work/digitalcorps.gsa.gov/digitalcorps.gsa.gov/node_modules/ws/lib/event-target.js:120:16)
    at WebSocket.emit (events.js:400:28)
    at Receiver.receiverOnMessage (/home/runner/work/digitalcorps.gsa.gov/digitalcorps.gsa.gov/node_modules/ws/lib/websocket.js:789:20)
    at Receiver.emit (events.js:400:28)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:1714) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:1714) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

## To Reproduce

See build Action results history.
Example: https://github.com/GSA/digitalcorps.gsa.gov/runs/3375873060?check_suite_focus=true

## Expected behavior

A11y tests do not crash due to this upstream `puppeteer` bug.

## Workaround

Re-run Action manually until it passes.

**Comment by DaveSkender** [comment]
```
 > http://localhost:4000/ - Failed to run
(node:3841) UnhandledPromiseRejectionWarning: Error: Protocol error (Target.disposeBrowserContext): Failed to find context with id 838F6AC920AC26316026C9A77B5DE1B5
    at /home/runner/work/digitalcorps.gsa.gov/digitalcorps.gsa.gov/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:71:63
    at new Promise (<anonymous>)
    at Connection.send (/home/runner/work/digitalcorps.gsa.gov/digitalcorps.gsa.gov/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:70:16)
    at Browser._disposeContext (/home/runner/work/digitalcorps.gsa.gov/digitalcorps.gsa.gov/node_modules/puppeteer/lib/cjs/puppeteer/common/Browser.js:168:32)
    at BrowserContext.close (/home/runner/work/digitalcorps.gsa.gov/digitalcorps.gsa.gov/node_modules/puppeteer/lib/cjs/puppeteer/common/Browser.js:523:29)
    at testRunner (/home/runner/work/digitalcorps.gsa.gov/digitalcorps.gsa.gov/node_modules/pa11y-ci/lib/pa11y-ci.js:135:21)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:3841) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:3841) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
